export { BaseConsumer, defaultDedupKey } from './streams/base-consumer.js'
export type { DedupOptions } from './streams/base-consumer.js'
export { redriveDlq, dlqStreamKey, idemKey, DlqMessageSchema, DlqReasonSchema, routeToDlq, DLQ_MAXLEN } from './streams/dlq.js'
export type { DlqRedis, DlqMessage, DlqReason, RedriveOptions, RedriveResult, DlqPublisher } from './streams/dlq.js'
export { RedisEventBus } from './streams/event-bus.js'
export type { EventBus, PublishOptions, StreamConsumerPort, RequestReplyPort, RawStreamReply } from './streams/event-bus.js'
export { validateWorkspaceRoot, resolveWorkspaceRoot } from './workspace-guard.js'
export { baseAgentSchema, baseAgentEnv, makeAgentConfig, loadAgentConfig, readSecretEnv } from './config/agent-config.js'
export type { AgentConfig } from './config/agent-config.js'
export { SessionDispatcher } from './streams/session-dispatcher.js'
export { runProbes, summarize, readinessResult, redisPingProbe, loopProbe, pgProbe, agentReadinessProbes, DEFAULT_PROBE_TIMEOUT_MS } from './health/readiness.js'
export { registerHealthRoutes, type HealthRouteOptions, type HealthRouteRegistrar, type HealthReply } from './health/routes.js'
export { buildProbes } from './health/readiness.js'
export type { CheckStatus, CheckResult, ReadinessReport, ReadinessProbe, ProbeDeps } from './health/readiness.js'
export type { ConsumerLike } from './streams/session-dispatcher.js'
export { GatewayStartSchema, GatewayEndSchema } from './streams/session-dispatcher.js'
export { AgentQuery, AgentQuerySchema, parseAgentQuery, collaborationPayloadFields } from './types/agent-query.js'
export type { AgentQueryKind, AgentQueryPayload } from './types/agent-query.js'
export { answerViaClaude, callClaudeText, callClaudeTextWithUsage, extractClaudeText, stripJsonFences } from './claude/answer-query.js'
export type { ClaudeLike, ClaudeTextWithUsage } from './claude/answer-query.js'
export { parseKnowledgeArray, extractKnowledgeViaClaude } from './claude/knowledge.js'
export { runCollaborativeHandle, makeCollaborationContext, createCollaborativeHandler } from './streams/collaboration.js'
export type { MainOutcome, CollabMessage, MessageBase, CollaborativeAgentDeps } from './streams/collaboration.js'
export { formatDomainKnowledge } from './prompt/domain-knowledge.js'
export { EventEnvelopeSchema, makeEnvelope } from './types/event-envelope.js'
export type { EventEnvelope, EnvelopeParts, EnvelopedMessage } from './types/event-envelope.js'
export { WorkPackageSchema, WpRiskSchema, AttributionCountersSchema } from './types/work-package.js'
export type { WorkPackage, WpRisk } from './types/work-package.js'
export { WP_STATES, WpStatusSchema, WP_TRANSITIONS, WP_INFLIGHT_STATES, canTransition, isTerminalWpState, assertWpTransition } from './types/wp-state.js'
export type { WpStatus } from './types/wp-state.js'
export { buildTaskGraph, detectCycle, topoSort, isReady, readyNodes } from './task-graph/index.js'
export type { TaskGraph, ReadinessOptions } from './task-graph/index.js'
export { oracleSatisfiedSet } from './task-graph/index.js'
export type { ApprovedOracleView } from './task-graph/index.js'
export { coverageMatrix, contentHashId, mergeKeepInflight } from './decomposition/index.js'
export type { StoryCoverage, CoverageMatrix, WpHashInput, MergeOptions } from './decomposition/index.js'
export { costOf, MODEL_PRICING, BudgetCircuitBreaker, BudgetExceededError } from './budget/index.js'
export type { ModelPrice, TokenUsage, BudgetCircuitOptions, BudgetRecordResult, BudgetSnapshot, BudgetScope } from './budget/index.js'
export { ProviderCircuitBreaker, ProviderCircuitOpenError, Bulkhead } from './resilience/index.js'
export type { CircuitState, ProviderCircuitOptions, ProviderCircuitSnapshot, BulkheadOptions, BulkheadSnapshot } from './resilience/index.js'
export { desiredMode, nextMode } from './resilience/index.js'
export type { OperationalMode, ModeSignals, ModeTransitionInput, ModeTransitionResult } from './resilience/index.js'
export {
  confidenceFromSupport, aggregateDimension, combineRisk, routeModels, evaluateHumanGate, scoreClassification,
  RISK_DIMENSIONS, ROUTED_AGENTS, RiskClassificationSchema, ClaimSchema, DimensionScoreSchema,
} from './risk/index.js'
export type {
  RiskDimension, RoutedAgent, ModelTier, ClaimInput, Claim, DimensionScore, RiskClassification, ScoreInput,
} from './risk/index.js'
