export { BaseConsumer, defaultDedupKey } from './streams/base-consumer.js'
export type { DedupOptions } from './streams/base-consumer.js'
export { RedisEventBus } from './streams/event-bus.js'
export type { EventBus, PublishOptions, StreamConsumerPort, RequestReplyPort, RawStreamReply } from './streams/event-bus.js'
export { validateWorkspaceRoot, resolveWorkspaceRoot } from './workspace-guard.js'
export { SessionDispatcher } from './streams/session-dispatcher.js'
export type { ConsumerLike } from './streams/session-dispatcher.js'
export { AgentQuery, AgentQuerySchema, parseAgentQuery, collaborationPayloadFields } from './types/agent-query.js'
export type { AgentQueryKind, AgentQueryPayload } from './types/agent-query.js'
export { answerViaClaude, callClaudeText, extractClaudeText, stripJsonFences } from './claude/answer-query.js'
export type { ClaudeLike } from './claude/answer-query.js'
export { parseKnowledgeArray, extractKnowledgeViaClaude } from './claude/knowledge.js'
export { runCollaborativeHandle, makeCollaborationContext, createCollaborativeHandler } from './streams/collaboration.js'
export type { MainOutcome, CollabMessage, MessageBase, CollaborativeAgentDeps } from './streams/collaboration.js'
export { formatDomainKnowledge } from './prompt/domain-knowledge.js'
export { EventEnvelopeSchema, makeEnvelope } from './types/event-envelope.js'
export type { EventEnvelope, EnvelopeParts, EnvelopedMessage } from './types/event-envelope.js'
export { WorkPackageSchema } from './types/work-package.js'
export type { WorkPackage } from './types/work-package.js'
export { buildTaskGraph, detectCycle, topoSort, isReady, readyNodes } from './task-graph/index.js'
export type { TaskGraph, ReadinessOptions } from './task-graph/index.js'
export { oracleSatisfiedSet } from './task-graph/index.js'
export type { ApprovedOracleView } from './task-graph/index.js'
export { coverageMatrix, contentHashId, mergeKeepInflight } from './decomposition/index.js'
export type { StoryCoverage, CoverageMatrix, WpHashInput, MergeOptions } from './decomposition/index.js'
