export {
  confidenceFromSupport,
  aggregateDimension,
  combineRisk,
  routeModels,
  evaluateHumanGate,
  scoreClassification,
  RISK_DIMENSIONS,
  ROUTED_AGENTS,
  FULL_CONFIDENCE_SUPPORT,
  MEDIUM_SCORE_THRESHOLD,
  HIGH_SCORE_THRESHOLD,
  STAKES_SCORE_THRESHOLD,
  LOW_CONFIDENCE_THRESHOLD,
  RiskClassificationSchema,
  ClaimSchema,
  DimensionScoreSchema,
} from './risk-classification.js'
export type {
  RiskDimension,
  RoutedAgent,
  ModelTier,
  ClaimInput,
  Claim,
  DimensionScore,
  RiskClassification,
  CombineOptions,
  RouteOptions,
  ScoreInput,
} from './risk-classification.js'
